---
title: "HW5 Part 2"
author: "Rick Farouni"
date: "November 29, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Question 2 (SEM)

For this part of the assignment, we are going to analyze a dataset taken from [the 2008 Cooperative Campaign Analysis Project (CCAP)](http://isps.yale.edu/research/data/d130). The dataset was used in the attached paper by Gerber *et al*, which you can refer to for ideas. I have selected a subset of the variables and also pre-processed the data such that observations with missing values, skipped questions, or unsure answers were removed. The resulting dataset includes 1568 observations on 57 variables. The first 44 variables make up the Big Five Inventory items. These are followed by 2 variables assessing social attitudes, 2 variables assessing economic attitudes, 3 variables assessing political ideology, and 6 demographic variables. 

There are two datasets provided: *"bfg.csv"* and *"bfg_numeric.csv"*. The categorical variables in *"bfg_numeric.csv"* have been tranformed into numeric type data. You should use *"bfg_numeric.csv"* for the analysis, but consult *"bfg.csv"* to understand what the numbers denote. To understand what the 44 BFI variables refer to, consult the *BFI.pdf* file provided. I gave the remaining variables descriptive labels. The structure of *"bfg_numeric.csv"* the dataset is as follows:

```
'data.frame':	1568 obs. of  57 variables:
 $ bfi_1                     : Factor w/ 5 levels "disagree strongly ",..: 5 5 2 2 2 2 3 5 3 5 ...
 $ bfi_2                     : Factor w/ 5 levels "disagree strongly ",..: 3 2 4 1 2 1 3 3 1 2 ...
 $ bfi_3                     : Factor w/ 5 levels "disagree strongly ",..: 5 5 4 3 3 5 5 5 5 5 ...
 $ bfi_4                     : Factor w/ 5 levels "disagree strongly ",..: 1 1 1 1 1 4 2 3 3 1 ...
 $ bfi_5                     : Factor w/ 5 levels "disagree strongly ",..: 3 4 3 5 4 3 3 5 5 4 ...
 $ bfi_6                     : Factor w/ 5 levels "disagree strongly ",..: 2 1 5 4 4 5 5 1 4 4 ...
 $ bfi_7                     : Factor w/ 5 levels "disagree strongly ",..: 5 3 4 3 5 5 3 3 4 4 ...
 $ bfi_8                     : Factor w/ 5 levels "disagree strongly ",..: 4 1 3 3 4 4 2 2 4 1 ...
 $ bfi_9                     : Factor w/ 5 levels "disagree strongly ",..: 5 2 4 4 5 1 3 1 5 3 ...
 $ bfi_10                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 4 2 5 5 5 5 5 4 ...
 $ bfi_11                    : Factor w/ 5 levels "disagree strongly ",..: 5 2 4 5 4 2 2 4 4 4 ...
 $ bfi_12                    : Factor w/ 5 levels "disagree strongly ",..: 1 1 1 4 1 3 1 2 1 1 ...
 $ bfi_13                    : Factor w/ 5 levels "disagree strongly ",..: 5 5 5 5 5 5 5 5 4 5 ...
 $ bfi_14                    : Factor w/ 5 levels "disagree strongly ",..: 4 4 4 2 1 5 5 4 4 3 ...
 $ bfi_15                    : Factor w/ 5 levels "disagree strongly ",..: 2 4 3 5 4 5 3 5 5 3 ...
 $ bfi_16                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 3 5 3 3 2 4 4 4 ...
 $ bfi_17                    : Factor w/ 5 levels "disagree strongly ",..: 4 4 4 4 5 3 2 3 5 4 ...
 $ bfi_18                    : Factor w/ 5 levels "disagree strongly ",..: 1 2 1 3 4 1 4 2 4 1 ...
 $ bfi_19                    : Factor w/ 5 levels "disagree strongly ",..: 4 2 3 4 2 5 4 3 3 3 ...
 $ bfi_20                    : Factor w/ 5 levels "disagree strongly ",..: 5 3 4 5 4 4 4 5 5 5 ...
 $ bfi_21                    : Factor w/ 5 levels "disagree strongly ",..: 1 3 5 3 4 5 5 1 4 3 ...
 $ bfi_22                    : Factor w/ 5 levels "disagree strongly ",..: 4 4 4 5 3 4 3 4 4 5 ...
 $ bfi_23                    : Factor w/ 5 levels "disagree strongly ",..: 1 2 1 3 4 2 2 1 3 1 ...
 $ bfi_24                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 5 4 5 2 3 3 5 5 ...
 $ bfi_25                    : Factor w/ 5 levels "disagree strongly ",..: 1 4 4 5 4 3 4 4 5 5 ...
 $ bfi_26                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 2 5 1 4 2 5 4 4 ...
 $ bfi_27                    : Factor w/ 5 levels "disagree strongly ",..: 1 1 4 5 3 2 4 2 3 2 ...
 $ bfi_28                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 5 4 4 4 5 5 4 5 ...
 $ bfi_29                    : Factor w/ 5 levels "disagree strongly ",..: 1 1 4 4 1 5 4 3 3 3 ...
 $ bfi_30                    : Factor w/ 5 levels "disagree strongly ",..: 4 4 5 5 5 3 5 5 4 3 ...
 $ bfi_31                    : Factor w/ 5 levels "disagree strongly ",..: 4 3 4 4 4 5 5 1 4 2 ...
 $ bfi_32                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 4 5 5 5 3 3 5 5 ...
 $ bfi_33                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 4 5 4 4 4 3 4 5 ...
 $ bfi_34                    : Factor w/ 5 levels "disagree strongly ",..: 4 3 4 5 5 2 5 4 5 4 ...
 $ bfi_35                    : Factor w/ 5 levels "disagree strongly ",..: 5 3 2 3 1 3 3 1 2 3 ...
 $ bfi_36                    : Factor w/ 5 levels "disagree strongly ",..: 5 4 3 5 4 2 2 4 4 5 ...
 $ bfi_37                    : Factor w/ 5 levels "disagree strongly ",..: 1 2 3 2 1 3 3 2 3 1 ...
 $ bfi_38                    : Factor w/ 5 levels "disagree strongly ",..: 4 4 3 4 5 3 4 3 3 5 ...
 $ bfi_39                    : Factor w/ 5 levels "disagree strongly ",..: 1 4 2 3 1 4 3 4 2 3 ...
 $ bfi_40                    : Factor w/ 5 levels "disagree strongly ",..: 4 4 3 5 5 4 4 5 5 4 ...
 $ bfi_41                    : Factor w/ 5 levels "disagree strongly ",..: 3 2 2 5 1 3 1 1 2 4 ...
 $ bfi_42                    : Factor w/ 5 levels "disagree strongly ",..: 5 5 4 5 5 4 4 4 4 5 ...
 $ bfi_43                    : Factor w/ 5 levels "disagree strongly ",..: 4 3 4 4 3 2 3 1 4 2 ...
 $ bfi_44                    : Factor w/ 5 levels "disagree strongly ",..: 3 4 4 5 4 2 4 5 4 3 ...
 $ AgainstAbortion           : Factor w/ 4 levels "abortion should always be legal.",..: 1 2 3 3 1 2 2 2 1 4 ...
 $ AgainstGayMarriage        : Factor w/ 4 levels "strongly favor",..: 1 1 1 2 1 1 2 1 1 4 ...
 $ AgainstUniversalHealthcare: Factor w/ 3 levels "gov should provide everyone with health care",..: 1 1 1 2 ... 
 $ AgainstTaxingTheRich      : Factor w/ 4 levels "strongly favor",..: 2 2 1 1 1 1 2 1 1 1 ...
 $ ConservativeIdeology      : Factor w/ 5 levels "very liberal",..: 1 3 3 1 1 3 3 1 2 4 ...
 $ PoliticalInterest         : Factor w/ 3 levels "very much interested",..: 1 2 2 2 1 1 1 1 1 1 ...
 $ Vote                      : Factor w/ 4 levels "i voted for barack obama",..: 1 1 2 2 1 2 2 1 1 2 ...
 $ YearOfBirth               : num  1962 1938 1948 1945 1951 ...
 $ Gender                    : Factor w/ 2 levels "male","female": 1 1 2 1 2 1 2 2 1 1 ...
 $ Race                      : Factor w/ 4 levels "white","black",..: 1 1 1 3 1 1 1 1 1 1 ...
 $ EducationLevel            : Factor w/ 6 levels "no hs","high school graduate",..: 6 6 5 3 6 3 6 6 5 3 ...
 $ IncomeLevel               : Factor w/ 14 levels "less than $10,000",..: 6 12 9 13 13 7 9 6 11 9 ...
 $ State                     : Factor w/ 49 levels "alabama","alaska",..: 9 5 42 3 3 3 22 21 21 1 ...
```

### Question 2a  

Fit a multiple factor analysis model using the data for 44 BFI variables only. A model with how many factors provides the best fit for the data? Criticise your model and the Big Five model framework in general. Consult the attached paper by Vassend and Skrondal for hints. Note that the about 16 of the 44 variables need to be reverse coded (e.g. 5 is mapped to 1, 1 mapped to 5, 4 mapped to 2, ...) 


### Question 2b

Explore structural relations between the Big Five factors and the other outcome variables measured in the dataset (e.g. political attitudes demographics). Ask a question, form a hypothesis, specify the corresponding SEM model (ideally in matrix form), then fit it to the data. You can use as many outcome variables as you would like, but make sure that what you end up doing makes sense. For example, fitting a model in which personality traits predict gender is not advised. Note that none of the variables in the dataset are really continous. Does the model you fit assume normally distributed data defined on the entire real line?  


____________________________________________________________


