---
title: "Factor Analysis Example"
output: html_document
geometry: margin=0.5in, voffset=0in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
options(digits = 3)
```


1. Load required libraries
```{r , message=FALSE}
library(lavaan)
library(semPlot)
```

2. Read in summary data

```{r }
# Spearman's data
fa_lower <- '
   1  
  .83   1  
  .78  .67   1  
  .70  .67  .64   1  
  .66  .65  .54  .45   1
  .68  .57  .51  .51 .40   1'

fa_cor <- getCov(fa_lower,
                  names = c("Classics","French","English","Math", "Tone_Dis", "Music"))
```

3. Specify model

```{r }
fa_model <- 'g =~ Classics + French + English + Math + Tone_Dis + Music'
```

4. Fit the model with the standardized latent variable option

```{r , message = FALSE }

fa_model_fit <- cfa(model = fa_model,
                    sample.cov = fa_cor, 
                    sample.nobs = 36, 
                    std.lv = TRUE)

summary(fa_model_fit , rsquare = TRUE)

```

5. Output the list of model matrices

```{r }
(modelEst1 <- lavInspect(fa_model_fit, "est"))
```

6. Plot path diagram
```{r }
semPaths(fa_model_fit,
         "par",
         layout = "tree")
```

